### ISSUE TITLE
volcano block doesn't even start working

### ISSUE THREAD

**Issue by elementhor218** [al132mc/Volcano-Block#128]
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
is this sth about my Launcher

**Comment by al132mc** [comment]
This most likely indicates that you are trying to run the modpack with java 9+, please make sure that your launcher is using java 8. You will have the same issue if you try to run any other 1.12 modpacks.

**Comment by elementhor218** [comment]
Minecraft process ID: 2180


Process crashed with exitcode -1073740791.
now it doesn't even give the crashing part but still it crushes,sadly.

**Comment by elementhor218** [comment]
btw thank you @al132mc it was because my minecraft launcher and I got the original so there is no problem. Have a great day
